config/routes.rb
Rails.application.routes.draw do
  get 'reserve_room/index'
  post 'reserve_room/confirm'
  get 'reserve_room/confirm'
  post 'reserve_room/show', to: 'reserve_room#create'
  get 'reserve_room/show'
  root 'rooms#top'
  get 'users/account'
  get 'users/profile'
  patch 'users/profile', to: 'users#update'
  get 'rooms/posts'
  get 'rooms/search/result', to: 'rooms#search'
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserve_room.rb
class ReserveRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, :room_id, :start_date, :end_date, :sum_price, presence: true
  validate :start_date_cannot_be_in_the_past, :end_date_cannot_be_in_start_date

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, ": 過去の日付は使えません")
    end
  end

  def end_date_cannot_be_in_start_date
    if end_date.present? && end_date < start_date
      errors.add(:end_date, ": 開始日より前の日付は使えません")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :reserve_rooms

  validates :user_id, :name, :introduction, :price, :address, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :icon
  has_many :rooms
  has_many :reserve_rooms

  validates :name, presence: true
  validates :introduction, length:{maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramaters, if: :devise_controller?

  protected

  def configure_permitted_paramaters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/reserve_room_controller.rb
class ReserveRoomController < ApplicationController
  def index
    @reserve_rooms = ReserveRoom.where(user_id: current_user.id)
  end

  def confirm
      @reserve_room = ReserveRoom.new(params.permit(:room_id, :start_date, :end_date, :people ))
      @room_price = @reserve_room.room.price
      @room_start = @reserve_room.start_date
      @room_end = @reserve_room.end_date
      @room_day = (@reserve_room.end_date - @reserve_room.start_date).to_i
      @room_people = @reserve_room.people
      @room_sum = @reserve_room.room.price * @reserve_room.people * @room_day
  end

  def create
    @reserve_room = ReserveRoom.new(params.require(:reserve_room).permit(:user_id, :room_id, :start_date, :end_date, :people, :sum_price ))
    if @reserve_room.save
      flash[:notice] = "予約が完了しました"
      redirect_to reserve_room_show_path
    else
      flash[:danger] = @reserve_room.errors.full_messages.join('<br>')
      redirect_to room_path(@reserve_room.room_id)
    end
  end

  def show
    @reserve_room = ReserveRoom.order("created_at DESC").first
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def top
  end

  def index
    @rooms = Room.all
  end

  def search
    if params[:flag]
      @rooms = Room.where("name LIKE ? OR address LIKE ? OR introduction LIKE ? OR price LIKE ?", "%#{params[:word]}%", "%#{params[:word]}%", "%#{params[:word]}%", "%#{params[:word]}%")
    else
      @rooms = Room.where("address LIKE ?", "%#{params[:word]}%")
    end
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:user_id, :name, :introduction, :price, :address, :image))
    if @room.save
      flash[:notice] = "ルームを新しく登録しました"
      redirect_to :rooms
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def posts
    @rooms = Room.where(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
  end

  def profile
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(params.require(:user).permit(:name,:icon,:introduction))
      flash[:notice] = "プロフィールを更新しました"
      redirect_to users_account_path
    else
      render users_profile_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reserve_room_helper.rb
module ReserveRoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="reset">
    <header class="header_width" >
      <div class="logo_area">
        <%= link_to root_path, class: "link_deco_none" do %>
          <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="ポテパンシェア" >
        <% end %>
        <%= form_with url: "/rooms/search/result", method: :get do |f| %>
          <%= f.text_field :word, placeholder: "エリアで検索" %>
        <% end %>
        <%= form_with url: "/rooms/search/result", method: :get do |f| %>
          <%= f.hidden_field :flag, :value => true %>
          <%= f.text_field :word, placeholder: "キーワードで検索" %>
        <% end %>
      </div>
      <div class="btn_area">
        <% if user_signed_in? %>
          <span class="header_user_name"><%= current_user.name %></span>
          <label for="menu_icon" >
            <% if current_user.icon.present? %>
              <%= image_tag current_user.icon, class: "icon_img" %>
            <% else %>
              <%= image_tag 'default.jpeg', class: "icon_img" %>
            <% end %>
          </label>
          <input type="checkbox" id="menu_icon" />
          <nav id="menu_bar">
            <ul class="menu">
              <li><%= link_to "ルーム登録", new_room_path %></li>
              <li><%= link_to "予約済みルーム一覧", reserve_room_index_path%></li>
              <li><%= link_to "登録済みルーム一覧", rooms_posts_path %></li>
              <li><%= link_to "設定", users_account_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </nav>
        <% else %>
          <%= link_to "ログイン", user_session_path, class: "btn_login" %>
          <%= link_to "登録する", new_user_registration_path, class: "btn_signup" %>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer class="footer_width">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/reserve_room/confirm.html.erb
<div class="reserve_confirm_area">
<%= form_with model:@reserve_room, url: reserve_room_show_path do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_id, value: @reserve_room.room_id %>
  <%= f.hidden_field :people, value: @room_people %>
  <%= f.hidden_field :sum_price, value: @room_sum %>
  <ul class="reserve_confirm_list">
        <li><h2>予約内容確認</h2></li>
        <li><h3><%= @room_price %>/日</h3></li>
        <li><%= f.label :start_date, "開始日" %></li>
        <li><%= f.date_field :start_date, value: @room_start, readonly: true %></li>
        <li><%= f.label :end_date, "終了日" %></li>
        <li><%= f.date_field :end_date, value: @room_end, readonly: true %></li>
        <li>使用日数：<%= @room_day %>日</li>
        <li>人数：<%= @room_people %>人</li>
        <li>合計金額</li>
        <li><%= @room_sum %>円</li>
        <li>上記内容でよろしければ「予約を確定」を押してください</li>
        <li><%= f.submit "予約を確定", class: "btn_submit" %></li>
        <li><%= link_to "戻る", "/rooms/#{@reserve_room.room_id}", class: "btn_back" %></li>
  </ul>
<% end %>
</div>

app/views/reserve_room/index.html.erb
<div class="room_posts_content">
<h2>予約済みルーム一覧</h2>
  <table>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>予約確定日時</th>
    </tr>
    <% @reserve_rooms.each do |room| %>
    <tr>
      <td>
        <%= link_to room.room, class: "link_deco_none" do %><%= image_tag room.room.image %><% end %>
      </td>
      <td>
        <%= link_to room.room do %><%= room.room.name %><% end %>
      </td>
      <td><%= room.room.introduction %></td>
      <td>¥<%= room.sum_price %></td>
      <td><%= room.start_date%></td>
      <td><%= room.end_date %></td>
      <td><%= room.created_at %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/reserve_room/show.html.erb
<%= render "shared/flash" %>
<div class="reserve_room">
  <table>
    <tr>
      <th>予約した部屋</th>
      <td><%= @reserve_room.room.name %></td>
    </tr>
    <tr>
      <th>開始日</th>
      <td><%= @reserve_room.start_date %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td><%= @reserve_room.end_date %></td>
    </tr>
    <tr>
      <th>価格</th>
      <td><%= @reserve_room.sum_price %>円</td>
    </tr>
  </table>
</div>

app/views/rooms/index.html.erb
<div class="content_width">
  <%= render "shared/flash" %>
  <div class="content_index">
    <div class="search_result">
      <h2>検索結果：</h2>
    </div>
    <% @rooms.each do |room| %>
      <%= link_to room, class: "link_deco_none" do %>
        <div class="content_blook">
          <%= image_tag room.image%>
          <p>
            <span class="room_title_font"><%= room.name %></span>
          </p>
          <p>
            <%= room.address %>
          </p>
          <span class="room_price_font"><p><%= room.price %></p></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="content_line">
  <div class="content_side">
    <h3>基本情報</h3>
  </div>
  <div class="content_main">
    <%= render "shared/error_messages", obj: @room %>
    <%= form_with model:@room do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <table class="room_info_table">
      <tr>
        <th><h2>ルーム情報登録</h2></th>
      </tr>
      <tr>
        <th><%= f.label :name, "ルーム名" %><span class="red_mark"></span></th>
        <td><%= f.text_field :name, placeholder:"ルーム名を入力" %></td>
      </tr>
      <tr>
        <th><%= f.label :introduction, "ルーム紹介" %><span class="red_mark"></span></th>
        <td><%= f.text_area :introduction, placeholder: "ルーム紹介を入力" %></td>
      </tr>
      <tr>
        <th><%= f.label :price, "料金" %><span class="red_mark"></span></th>
        <td><%= f.text_field :price, placeholder: "一日あたりの料金を入力" %></td>
      </tr>
      <tr>
        <th><%= f.label :address, "住所" %><span class="red_mark"></span></th>
        <td><%= f.text_field :address, placeholder: "住所を入力" %></td>
      </tr>
      <tr>
        <th><%= f.label :image, "ルーム画像" %><span class="red_mark"></span></th>
        <td><%= f.file_field :image %></td>
      </tr>
      <tr>
        <th colspan="2"><%= f.submit "登録", class: "btn_submit" %></th>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/rooms/posts.html.erb
<div class="room_posts_content">
<h2>登録済みルーム一覧</h2>
  <table>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
    <% @rooms.each do |room| %>
    <tr>
      <td>
        <%= link_to room, class: "link_deco_none" do %><%= image_tag room.image %><% end %>
      </td>
      <td>
        <%= link_to room do %><%= room.name %><% end %>
      </td>
      <td><%= room.introduction %></td>
      <td>¥<%= room.price %></td>
      <td><%= room.created_at%></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="content_width">
  <div class="content_index">
    <div class="search_result">
      <h2>検索結果：<%= @rooms.count %>件</h2>
    </div>
    <% @rooms.each do |room| %>
      <%= link_to room, class: "link_deco_none" do %>
        <div class="content_blook">
          <%= image_tag room.image%>
          <p>
            <span class="room_title_font"><%= room.name %></span>
          </p>
          <p>
            <%= room.address %>
          </p>
          <span class="room_price_font"><p><%= room.price %></p></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<%= render 'shared/flash_danger' %>
<div class="show_room">
  <%= image_tag @room.image %>
  <div class="price_form">
    <h3>¥<%= @room.price %>/日</h3>
    <%= form_with(url: reserve_room_confirm_path, method: :get) do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <ul class="price_form_list">
        <li><%= f.label :start_date, "開始日" %></li>
        <li><%= f.date_field :start_date, value: Date.today %></li>
        <li><%= f.label :end_date, "終了日" %></li>
        <li><%= f.date_field :end_date, value: Date.today + 1 %></li>
        <li><%= f.label :people, "人数" %></li>
        <li><%= f.number_field :people, value: 1, min: 1 %></li>
        <li><%= f.submit "予約する", class: "btn_submit" %></li>
      </ul>
    <% end %>

  </div>
<table class="show_room_table">
  <tr>
    <td rowspan="2", id="user_img">イメージ</td>
    <td><%= @room.name %></td>
  </tr>
  <tr>
    <td><%= @room.address %></td>
  </tr>
  <tr>
    <td colspan="2", id="under_line"><%= @room.introduction %></td>
  <tr>
</table>
</div>

app/views/rooms/top.html.erb
<%= render "shared/flash" %>
<div class="top_img">
  <div class="top_content_right">
    <div class="search_area">
      <div class="search_area_content">
        <span>Potepan Shareでまだ体験したことない旅をしよう</span>
        <%= form_with url: "/rooms/search/result", method: :get do |f| %>
          <%= f.label :word, "エリア" %>
          <%= f.text_field :word, placeholder: "東京" %>
          <%= f.submit "探す", class: "btn_submit" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="top_category">
  <h2>おすすめのエリア</h2>
  <div class="top_category_box_area">
    <%= link_to rooms_search_result_path(word: "東京"), class: "top_category_box" do %><span>東京</span><% end %>
    <%= link_to rooms_search_result_path(word: "大阪"), class: "top_category_box" do %><span>大阪</span><% end %>
    <%= link_to rooms_search_result_path(word: "京都"), class: "top_category_box" do %><span>京都</span><% end %>
    <%= link_to rooms_search_result_path(word: "札幌"), class: "top_category_box" do %><span>札幌</span><% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul class="error_message">
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

app/views/shared/_flash_danger.html.erb
<% if flash[:danger] %>
  <p class="danger"><%= flash[:danger].html_safe %></p>
<% end %>

app/views/users/account.html.erb
<div class="content_line">
  <div class="content_side">
    <h3>アカウント</h3>
    <h4><%= link_to "プロフィール", users_profile_path, class: "link_deco_none" %></h4>
  </div>
  <div class="content_main">
  <%= render "shared/flash" %>
  <table class="account_table">
    <tr>
      <th><h2>アカウント</h2></th>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= current_user.email %></td>
    </tr>
    <tr>
      <th>パスワード</th>
      <td>* * * * * * * * *</td>
    </tr>
    <tr>
      <td colspan="2"><%= link_to "編集", edit_user_registration_path, class: "btn_submit" %></td>
    </tr>
  </table>
  </div>
</div>

app/views/users/profile.html.erb
<div class="content_line">
  <div class="content_side">
    <h4><%= link_to "アカウント", users_account_path, class: "link_deco_none" %></h4>
    <h3>プロフィール</h3>
  </div>
  <div class="content_main">
  <%= render "shared/error_messages", obj: @user %>
  <%= form_with model:@user, url: users_profile_path do |f| %>
  <table class="account_table">
    <tr>
      <th><h2>プロフィール</h2></th>
    </tr>
    <tr>
      <td colspan="2", class="icon_center" >
        <% if current_user.icon.present? %>
          <%= image_tag current_user.icon, class: "icon_img" %>
        <% else %>
          <%= image_tag 'default.jpeg', class: "icon_img" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :icon , "アイコン画像" %></th>
      <td><%= f.file_field :icon %></td>
    </tr>
    <tr>
      <th><%= f.label :name, "名前" %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :introduction, "自己紹介" %></th>
      <td><%= f.text_area :introduction, placeholder: "自己紹介を入力" %></td>
    </tr>
    <tr>
      <td colspan="2"><%= f.submit "更新", class: "btn_submit" %></td>
    </tr>
  </table>
  <% end %>
  </div>
</div>